### ISSUE TITLE
Filtering SNPs based on p-value

### ISSUE THREAD

**Issue by Al-Murphy** [yakirr/fcor#10]
Hi,

Thanks for this great tool! I am currently using it along with a GWAS sumstats dataset and a model similar to [Basset](https://github.com/davek44/Basset).

I want to follow the approach used in your paper (and in the example on this repo) to check for significant, genome-wide associations between transcription factor binding and cell types based on the GWAS SNPs. However, my issue is that the model takes a significant amount of time to predict the change in profiles based on the major and minor alleles (reference allele and SNP). To make this task quicker, I have already filtered these SNPs to just those present in the Hapmap3 1000 genomes dataset that you have provided [here](https://data.broadinstitute.org/alkesgroup/SLDP/refpanel/KG3.hm3.tar.gz).

However this is still too many SNPs to feasibly predict on with the model I'm using. I am now considering only predicting on SNPs that are of genome-wide significance in the GWAS sumstats. Is this an acceptable approach? Do you expect this to bias the results in any way?

Thanks!

**Comment by yakirr** [comment]
Hi Alan, I apologize for the delay here! I don't think this would bias the results of sldp by much -- the design of sldp makes the hypothesis test all about whether *directions* of effect align, and so you can pre-filter the SNPs in any way as long as that filtering isn't correlated with the directionality of their effect on trait.

One issue I can see arising, though I don't know how substantial it would be, is that SNPs that are GW-significant probably have a different MAF distribution than the entire set of causal SNPs. If you wanted to guard against this, you could add a few tracks to the sldp "background model" (which consists of a partition of all 1KG SNPs into 5 MAF bins) that consist of a similar MAF bin partition of your filtered set of SNPs.

I think if I were you I'd first try just running the software as is and then if you get hits then consider examining the MAF issue at that point.

Hope this helps,
Yakir

**Comment by Al-Murphy** [comment]
Thanks for this Yakir, it's very helpful!

I would like to test this filtering approach on the test data you provide in your minimal example. One practical question I had is whether I should filter out the SNPs from the GWAS sumstats as well as the annotations files? Or if this would even make a difference? 

I will update this issue with the results I find anyway - I guess if the filtering had little effect we should see a similar p-value (and z-score) of association of IRF1 binding across all the different filtering (and no filtering) levels.

Thanks again,
Alan.

**Comment by yakirr** [comment]
Hi Alan,

For Question (1):
For each chip-seq track, we only included in the annotation the SNPs that fall in that track's chip-seq peaks. See Equation (7) in the following excerpt from our paper:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/3740601/201395987-f1ede1e2-13fe-4ad2-9284-6710065f0bbf.png">
We did not retain the full set of SNP predictions outside the chip-seq peaks.

If you hadn't been implementing this in your pipeline though, I wonder if restricting to SNPs in peaks of some kind might help you save computation time?

For Question (2):
We didn't save the p-values for the sumstats because we work from the chi-squared statistics, but (maybe you already know this) you can convert the chi-squared statistics to p-values using a chi-squared test with 1 degree of freedom (see, e.g., [this example](https://stackoverflow.com/questions/11725115/p-value-from-chi-sq-test-statistic-in-python)).

Hope this helps,
Yakir

**Comment by Al-Murphy** [comment]
Hey Yakir,

Thanks for this, that all makes perfect sense!

I'll had a look at a few other TF binding SNP effect prediciton sets where there are more SNPs included. I tried SydhK562Pol2 but got a strange error when trying to run sldp on the filtered set:

```
bash sldp_commands/hm3_2216.sh 
=====
/home/aemurphy/anaconda3/envs/sldp/bin/sldp --pss-chr ./CD.KG3.95/ --sannot-chr ./SydhK562Pol2_hm3/ --outfile-stem /home/aemurphy/RDS/project/celltypeai/live/Projects/sldp_downsampling/results/hm3_2216 --config /home/aemurphy/RDS/project/celltypeai/live/Projects/sldp_downsampling/sldp.config.json --seed 2216 --bfile-reg-chr plink_files/1000G.EUR.QC.hm3_noMHC
=====
T                        1000000
background_sannot_chr    [u'maf5/']
bfile_chr                plink_files/1000G.EUR.QC.
bfile_reg_chr            plink_files/1000G.EUR.QC.hm3_noMHC
bothp                    False
chi2_thresh              0
chroms                   [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
config                   /home/aemurphy/RDS/project/celltypeai/live/Projects/sldp_downsampling/sldp.config.json
fastp                    False
jk_blocks                300
ld_blocks                pickrell_ldblocks.hg19.eur.bed
ldscores_chr             LDscore/LDscore.
more_stats               False
outfile_stem             /home/aemurphy/RDS/project/celltypeai/live/Projects/sldp_downsampling/results/hm3_2216
print_snps               1000G_hm3_noMHC.rsid
pss_chr                  ./CD.KG3.95/
refpanel_name            KG3.95
sannot_chr               ['./SydhK562Pol2_hm3/']
seed                     2216
stat                     sum
story_corr_thresh        0.8
sumstats_stem            None
svd_stem                 svds_95percent/
tell_me_stories          0.0
verbose_thresh           0.0
weights                  Winv_ahat_h
=====
Preprocessing ./SydhK562Pol2_hm3/ at chromosomes [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
Using config file /home/aemurphy/RDS/project/celltypeai/live/Projects/sldp_downsampling/sldp.config.json and default options
initializing...
1716 loci after removing MHC
1187349 print snps
5.96046447754e-06 : loading chr 1 of [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
Traceback (most recent call last):
  File "/home/aemurphy/anaconda3/envs/sldp/bin/sldp", line 380, in <module>
    preprocess_sannots(args)
  File "/home/aemurphy/anaconda3/envs/sldp/bin/sldp", line 286, in preprocess_sannots
    sldp.preprocessannot.main(args_)
  File "/home/aemurphy/anaconda3/envs/sldp/lib/python2.7/site-packages/sldp/preprocessannot.py", line 35, in main
    snps = refpanel.bim_df(c)
  File "/home/aemurphy/anaconda3/envs/sldp/lib/python2.7/site-packages/ypy/memo.py", line 32, in __call__
    value = self.func(*args)
  File "/home/aemurphy/anaconda3/envs/sldp/lib/python2.7/site-packages/gprim/dataset.py", line 50, in bim_df
    sep='\t')
  File "/home/aemurphy/anaconda3/envs/sldp/lib/python2.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/aemurphy/anaconda3/envs/sldp/lib/python2.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/aemurphy/anaconda3/envs/sldp/lib/python2.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/aemurphy/anaconda3/envs/sldp/lib/python2.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/aemurphy/anaconda3/envs/sldp/lib/python2.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: [Errno 2] File plink_files/1000G.EUR.QC.1.bim does not exist: 'plink_files/1000G.EUR.QC.1.bim'
```

The config file (sldp.config.json) contains:
```
{
    "print-snps":"1000G_hm3_noMHC.rsid",
    "bfile-chr":"plink_files/1000G.EUR.QC.",
    "bfile-reg-chr":"plink_files/1000G.EUR.QC.hm3_noMHC.",
    "ldscores-chr":"LDscore/LDscore.",
    "svd-stem":"svds_95percent/",
    "ld-blocks":"pickrell_ldblocks.hg19.eur.bed",
    "refpanel-name":"KG3.95",
    "background-sannot-chr":["maf5/"]
}
```

So I'm not sure why it looks for plink_files/1000G.EUR.QC. rather than plink_files/1000G.EUR.QC.hm3_noMHC.?

Strangly though when I don't filter this runs fine. The only difference is that the filtered run's sannot-chr folder only contains *.sannot.gz files not *.RV.gz or *.info files which are in the unfiltered. I thought these would be created within the run however? Or is this likely a red herring and could the issue be the number of SNP effect predictions just being too low? This is the number I have before and after filtering:
```
('1.sannot.gz', ' filtered from 2260 to 308 SNPs.')
('21.sannot.gz', ' filtered from 319 to 37 SNPs.')
('17.sannot.gz', ' filtered from 1295 to 157 SNPs.')
('4.sannot.gz', ' filtered from 765 to 88 SNPs.')
('9.sannot.gz', ' filtered from 785 to 88 SNPs.')
('18.sannot.gz', ' filtered from 328 to 40 SNPs.')
('13.sannot.gz', ' filtered from 276 to 25 SNPs.')
('16.sannot.gz', ' filtered from 1041 to 95 SNPs.')
('7.sannot.gz', ' filtered from 1201 to 114 SNPs.')
('15.sannot.gz', ' filtered from 676 to 85 SNPs.')
('14.sannot.gz', ' filtered from 529 to 78 SNPs.')
('22.sannot.gz', ' filtered from 452 to 53 SNPs.')
('11.sannot.gz', ' filtered from 1175 to 184 SNPs.')
('6.sannot.gz', ' filtered from 1708 to 110 SNPs.')
('5.sannot.gz', ' filtered from 917 to 117 SNPs.')
('19.sannot.gz', ' filtered from 1907 to 244 SNPs.')
('12.sannot.gz', ' filtered from 1075 to 124 SNPs.')
('10.sannot.gz', ' filtered from 970 to 104 SNPs.')
('8.sannot.gz', ' filtered from 818 to 89 SNPs.')
('20.sannot.gz', ' filtered from 568 to 53 SNPs.')
('3.sannot.gz', ' filtered from 1043 to 128 SNPs.')
('2.sannot.gz', ' filtered from 1291 to 138 SNPs.')
```
Apologies on this question but I've been struggling with this for quite some time now!

Cheers,
Alan.

**Comment by Al-Murphy** [comment]
Just as an update, copying over the *.info and *.RV.gz files from the full run stopped the error however copying either of the two by themselves still produces the error. Maybe I'm missing these reference files which can be downloaded? I followed the downloads in the [minimal example](https://github.com/yakirr/sldp/wiki/Minimal-example)
